import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { writeNitroStepEntrypoint } from "#internal/workflow-bundle/nitro-step-entry.js";

describe("writeNitroStepEntrypoint", () => {
  it("serializes Windows absolute imports as file URLs", async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), "eve-nitro-step-entry-windows-"));
    const outfile = join(tempRoot, "build", "steps.mjs");

    try {
      await writeNitroStepEntrypoint({
        builtinsPath: "G:\\projects\\eve\\node_modules\\eve\\dist\\builtins.js",
        discoveredEntries: {
          discoveredSerdeFiles: [],
          discoveredSteps: [],
        },
        outfile,
        preferAbsoluteFileImports: true,
        projectRoot: "G:\\projects\\eve",
        sideEffectFiles: [],
        workingDir: "G:\\projects\\eve",
      });

      await expect(readFile(outfile, "utf8")).resolves.toBe(
        [
          "// Generated by eve. Do not edit by hand.",
          'import "file:///G:/projects/eve/node_modules/eve/dist/builtins.js";',
          "export const __steps_registered = true;",
          "",
        ].join("\n"),
      );
    } finally {
      await rm(tempRoot, { force: true, recursive: true });
    }
  });

  it("does not rewrite the Nitro step entry when the content is unchanged", async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), "eve-nitro-step-entry-"));
    const stepsDirectory = join(tempRoot, "steps");
    const stepFilePath = join(stepsDirectory, "ping.ts");
    const outfile = join(tempRoot, "build", "steps.mjs");

    try {
      await mkdir(stepsDirectory, { recursive: true });
      await writeFile(
        stepFilePath,
        ["export async function ping() {", '  "use step";', '  return "pong";', "}", ""].join("\n"),
      );

      await writeNitroStepEntrypoint({
        discoveredEntries: {
          discoveredSerdeFiles: [],
          discoveredSteps: [stepFilePath],
        },
        outfile,
        projectRoot: tempRoot,
        sideEffectFiles: [],
        workingDir: tempRoot,
      });

      const firstSource = await readFile(outfile, "utf8");
      const firstWrite = await stat(outfile);

      await new Promise((resolve) => setTimeout(resolve, 25));

      await writeNitroStepEntrypoint({
        discoveredEntries: {
          discoveredSerdeFiles: [],
          discoveredSteps: [stepFilePath],
        },
        outfile,
        projectRoot: tempRoot,
        sideEffectFiles: [],
        workingDir: tempRoot,
      });

      const secondSource = await readFile(outfile, "utf8");
      const secondWrite = await stat(outfile);

      expect(secondSource).toBe(firstSource);
      expect(secondWrite.mtimeMs).toBe(firstWrite.mtimeMs);
    } finally {
      await rm(tempRoot, { force: true, recursive: true });
    }
  });
});
