import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";

import { normalizeEsmImportSpecifier } from "#internal/application/import-specifier.js";
import {
  applyWorkflowTransform,
  type WorkflowManifest,
} from "#internal/workflow-bundle/workflow-builders.js";

export interface NitroStepEntrypointDiscoveredEntries {
  readonly discoveredSerdeFiles: readonly string[];
  readonly discoveredSteps: readonly string[];
}

/**
 * Writes the hosted Nitro step entrypoint source and returns the manifest
 * metadata discovered from the imported step and serde files.
 */
export async function writeNitroStepEntrypoint(input: {
  readonly builtinsPath?: string;
  readonly discoveredEntries: NitroStepEntrypointDiscoveredEntries;
  readonly outfile: string;
  readonly preferAbsoluteFileImports?: boolean;
  readonly projectRoot: string;
  readonly sideEffectFiles: readonly string[];
  readonly workingDir: string;
}): Promise<WorkflowManifest> {
  const stepFiles = [...input.discoveredEntries.discoveredSteps].sort();
  const stepFileSet = new Set(stepFiles);
  const serdeOnlyFiles = [...input.discoveredEntries.discoveredSerdeFiles]
    .sort()
    .filter((filePath) => !stepFileSet.has(filePath));
  const manifest = await collectNitroStepManifest({
    projectRoot: input.projectRoot,
    stepFiles,
    serdeOnlyFiles,
    workingDir: input.workingDir,
  });
  const outfileDirectory = dirname(input.outfile);
  const builtinsImportSpecifier =
    input.builtinsPath === undefined
      ? "workflow/internal/builtins"
      : createFileImportSpecifier({
          outfileDirectory,
          preferAbsoluteFileImports: input.preferAbsoluteFileImports ?? false,
          targetPath: input.builtinsPath,
        });
  const importLines = createEntrypointImportLines({
    builtinsImportSpecifier,
    outfileDirectory,
    preferAbsoluteFileImports: input.preferAbsoluteFileImports ?? false,
    serdeOnlyFiles,
    sideEffectFiles: input.sideEffectFiles,
    stepFiles,
  });
  const lines = [
    "// Generated by eve. Do not edit by hand.",
    ...importLines,
    "export const __steps_registered = true;",
    "",
  ];
  const nextSource = lines.join("\n");

  await mkdir(outfileDirectory, { recursive: true });
  const existingSource = await readTextFileIfPresent(input.outfile);

  if (existingSource !== nextSource) {
    await writeFile(input.outfile, nextSource);
  }

  return manifest;
}

function createEntrypointImportLines(input: {
  readonly builtinsImportSpecifier: string;
  readonly outfileDirectory: string;
  readonly preferAbsoluteFileImports: boolean;
  readonly serdeOnlyFiles: readonly string[];
  readonly sideEffectFiles: readonly string[];
  readonly stepFiles: readonly string[];
}): readonly string[] {
  const importedModules = [
    input.builtinsImportSpecifier,
    ...input.sideEffectFiles.map((filePath) =>
      createFileImportSpecifier({
        outfileDirectory: input.outfileDirectory,
        preferAbsoluteFileImports: input.preferAbsoluteFileImports,
        targetPath: filePath,
      }),
    ),
    ...input.stepFiles.map((filePath) =>
      createFileImportSpecifier({
        outfileDirectory: input.outfileDirectory,
        preferAbsoluteFileImports: input.preferAbsoluteFileImports,
        targetPath: filePath,
      }),
    ),
    ...input.serdeOnlyFiles.map((filePath) =>
      createFileImportSpecifier({
        outfileDirectory: input.outfileDirectory,
        preferAbsoluteFileImports: input.preferAbsoluteFileImports,
        targetPath: filePath,
      }),
    ),
  ];

  return importedModules.map((importSpecifier) => `import ${JSON.stringify(importSpecifier)};`);
}

function createFileImportSpecifier(input: {
  readonly outfileDirectory: string;
  readonly preferAbsoluteFileImports: boolean;
  readonly targetPath: string;
}): string {
  if (input.preferAbsoluteFileImports) {
    return normalizeEsmImportSpecifier(input.targetPath);
  }

  return createRelativeImportSpecifier(input.outfileDirectory, input.targetPath);
}

async function collectNitroStepManifest(input: {
  readonly projectRoot: string;
  readonly serdeOnlyFiles: readonly string[];
  readonly stepFiles: readonly string[];
  readonly workingDir: string;
}): Promise<WorkflowManifest> {
  const manifest: WorkflowManifest = {};
  const files = [...input.stepFiles, ...input.serdeOnlyFiles];

  for (const filePath of files) {
    const source = await readFile(filePath, "utf8");
    const relativeFilepath = createManifestRelativeFilepath(input.workingDir, filePath);
    const transformed = await applyWorkflowTransform(
      relativeFilepath,
      source,
      "step",
      filePath,
      input.projectRoot,
    );

    mergeWorkflowManifest(manifest, transformed.workflowManifest);
  }

  return manifest;
}

function mergeWorkflowManifest(target: WorkflowManifest, source: WorkflowManifest): void {
  target.steps = mergeWorkflowManifestSection(target.steps, source.steps);
  target.workflows = mergeWorkflowManifestSection(target.workflows, source.workflows);
  target.classes = mergeWorkflowManifestSection(target.classes, source.classes);
}

function mergeWorkflowManifestSection<
  TSection extends Record<string, Record<string, object>> | undefined,
>(target: TSection, source: TSection): TSection {
  if (source === undefined) {
    return target;
  }

  const nextSection = {
    ...target,
  } as Record<string, Record<string, object>>;

  for (const [relativeFileName, entries] of Object.entries(source)) {
    nextSection[relativeFileName] = {
      ...nextSection[relativeFileName],
      ...entries,
    };
  }

  return nextSection as TSection;
}

function createManifestRelativeFilepath(workingDir: string, absolutePath: string): string {
  const normalizedFile = absolutePath.replaceAll("\\", "/");
  const normalizedWorkingDir = workingDir.replaceAll("\\", "/");
  let relativePath = relative(normalizedWorkingDir, normalizedFile).replaceAll("\\", "/");

  if (relativePath.startsWith("../")) {
    relativePath = relativePath
      .split("/")
      .filter((part) => part !== "..")
      .join("/");
  }

  return relativePath;
}

function createRelativeImportSpecifier(fromDirectoryPath: string, targetPath: string): string {
  const relativePath = relative(fromDirectoryPath, targetPath).replaceAll("\\", "/");

  if (relativePath.startsWith(".")) {
    return relativePath;
  }

  return `./${relativePath}`;
}

async function readTextFileIfPresent(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }

    throw error;
  }
}
