import { z } from "#compiled/zod/index.js";
import type { ModuleSourceRef } from "#shared/source-ref.js";
import type {
  CompiledAgentManifest,
  CompiledAgentNodeManifest,
  CompiledExtensionMount,
} from "#compiler/manifest.js";
import { ROOT_COMPILED_AGENT_NODE_ID } from "#compiler/manifest.js";
import { normalizeEsmImportSpecifier } from "#internal/application/import-specifier.js";

/**
 * Compiled module ownership for one runtime graph node.
 */
export type CompiledModuleNodeScope = z.infer<typeof compiledModuleNodeScopeSchema>;

/**
 * Flattened compiled authored module map keyed by stable node ids.
 */
export type CompiledModuleMap = z.infer<typeof compiledModuleMapSchema>;

const compiledModuleNodeScopeSchema = z
  .object({
    modules: z.record(z.string(), z.object({}).passthrough()),
  })
  .strict();

/**
 * Zod schema for the flattened compiled authored module map.
 */
export const compiledModuleMapSchema = z
  .object({
    nodes: z.record(z.string(), compiledModuleNodeScopeSchema),
  })
  .strict();

/**
 * Input for generating the compiled authored module map artifact.
 */
export interface CreateCompiledModuleMapSourceInput {
  /**
   * Controls how generated authored-module imports are written. Relative
   * specifiers are the compiler default; absolute specifiers are useful when a
   * bundler consumes the module map from a virtual module id.
   */
  importSpecifierStyle?: "absolute" | "relative";
  manifest: CompiledAgentManifest;
  moduleMapPath: string;
}

interface CollectedModuleImport {
  readonly bindingName: string;
  readonly importSpecifier: string;
  readonly sourceId: string;
}

interface CollectedModuleNodeScope {
  readonly modules: readonly CollectedModuleImport[];
  readonly nodeId: string;
}

/**
 * Generates the compiler-owned module map artifact that statically imports
 * every module-backed authored source.
 */
export function createCompiledModuleMapSource(input: CreateCompiledModuleMapSourceInput): string {
  const moduleMapDirectory = dirnameFilesystemPath(input.moduleMapPath);
  const importSpecifierStyle = input.importSpecifierStyle ?? "relative";
  let nextBindingIndex = 0;
  const collectedScopes: CollectedModuleNodeScope[] = [
    collectModuleNodeScope({
      agentRoot: input.manifest.agentRoot,
      importSpecifierStyle,
      manifest: input.manifest,
      moduleMapDirectory,
      nextBindingName() {
        return `module_${nextBindingIndex++}`;
      },
      nodeId: ROOT_COMPILED_AGENT_NODE_ID,
    }),
    ...[...input.manifest.subagents]
      .sort((left, right) => left.nodeId.localeCompare(right.nodeId))
      .map((subagent) =>
        collectModuleNodeScope({
          agentRoot: subagent.agent.agentRoot,
          importSpecifierStyle,
          manifest: subagent.agent,
          moduleMapDirectory,
          nextBindingName() {
            return `module_${nextBindingIndex++}`;
          },
          nodeId: subagent.nodeId,
        }),
      ),
  ];
  const allModules = collectedScopes.flatMap((scope) => scope.modules);

  const staticImports = allModules.map(
    (moduleImport) =>
      `import * as ${moduleImport.bindingName} from ${JSON.stringify(moduleImport.importSpecifier)};`,
  );

  return [
    "// Generated by eve. Do not edit by hand.",
    "",
    ...staticImports,
    ...(staticImports.length > 0 ? [""] : []),
    `export const moduleMap = ${renderModuleMap(collectedScopes)};`,
    "",
    "export default moduleMap;",
    "",
  ].join("\n");
}

function collectModuleNodeScope(input: {
  readonly agentRoot: string;
  readonly importSpecifierStyle: "absolute" | "relative";
  readonly manifest: CompiledAgentNodeManifest;
  readonly moduleMapDirectory: string;
  readonly nextBindingName: () => string;
  readonly nodeId: string;
}): CollectedModuleNodeScope {
  return {
    modules: collectModuleRefsForManifest(input.manifest)
      .sort((left, right) => left.sourceId.localeCompare(right.sourceId))
      .map((moduleSourceRef) => ({
        bindingName: input.nextBindingName(),
        importSpecifier: createImportSpecifier({
          fromDirectory: input.moduleMapDirectory,
          importSpecifierStyle: input.importSpecifierStyle,
          targetPath: joinFilesystemPath(input.agentRoot, moduleSourceRef.logicalPath),
        }),
        sourceId: moduleSourceRef.sourceId,
      })),
    nodeId: input.nodeId,
  };
}

/**
 * Collects every module-backed source reference from a single compiled
 * agent node manifest. Used by both the compiler (to generate the static
 * module-map artifact) and the runtime loader (to hydrate a module map
 * from the manifest when the pre-built artifact is unavailable).
 */
export function collectModuleRefsForManifest(
  manifest: CompiledAgentNodeManifest,
): ModuleSourceRef[] {
  const moduleSourceRefs = new Map<string, ModuleSourceRef>();

  if (manifest.config.source !== undefined) {
    moduleSourceRefs.set(manifest.config.source.sourceId, manifest.config.source);
  }

  if (manifest.config.model.source !== undefined) {
    moduleSourceRefs.set(manifest.config.model.source.sourceId, manifest.config.model.source);
  }

  for (const channel of manifest.channels) {
    // Disabled channel entries don't have a source module — they're a
    // marker that the matching framework default should be removed.
    if (channel.kind === "disabled") {
      continue;
    }
    moduleSourceRefs.set(channel.sourceId, {
      exportName: channel.exportName,
      sourceKind: "module",
      logicalPath: channel.logicalPath,
      sourceId: channel.sourceId,
    });
  }

  for (const connection of manifest.connections) {
    moduleSourceRefs.set(connection.sourceId, {
      exportName: connection.exportName,
      sourceKind: "module",
      logicalPath: connection.logicalPath,
      sourceId: connection.sourceId,
    });
  }

  for (const tool of manifest.tools) {
    moduleSourceRefs.set(tool.sourceId, {
      exportName: tool.exportName,
      sourceKind: "module",
      logicalPath: tool.logicalPath,
      sourceId: tool.sourceId,
    });
  }

  for (const dynamicInstruction of manifest.dynamicInstructions) {
    moduleSourceRefs.set(dynamicInstruction.sourceId, {
      exportName: dynamicInstruction.exportName,
      sourceKind: "module",
      logicalPath: dynamicInstruction.logicalPath,
      sourceId: dynamicInstruction.sourceId,
    });
  }

  for (const dynamicSkill of manifest.dynamicSkills) {
    moduleSourceRefs.set(dynamicSkill.sourceId, {
      exportName: dynamicSkill.exportName,
      sourceKind: "module",
      logicalPath: dynamicSkill.logicalPath,
      sourceId: dynamicSkill.sourceId,
    });
  }

  for (const dynamicTool of manifest.dynamicTools) {
    moduleSourceRefs.set(dynamicTool.sourceId, {
      exportName: dynamicTool.exportName,
      sourceKind: "module",
      logicalPath: dynamicTool.logicalPath,
      sourceId: dynamicTool.sourceId,
    });
  }

  for (const remoteAgent of manifest.remoteAgents) {
    moduleSourceRefs.set(remoteAgent.sourceId, {
      exportName: remoteAgent.exportName,
      sourceKind: "module",
      logicalPath: remoteAgent.logicalPath,
      sourceId: remoteAgent.sourceId,
    });
  }

  for (const hook of manifest.hooks) {
    moduleSourceRefs.set(hook.sourceId, {
      exportName: hook.exportName,
      sourceKind: "module",
      logicalPath: hook.logicalPath,
      sourceId: hook.sourceId,
    });
  }

  for (const schedule of manifest.schedules) {
    // Only `run`-handler schedules need their source loaded at dispatch
    // time. Markdown schedules execute from `manifest.markdown`.
    if (schedule.sourceKind !== "module" || !schedule.hasRun) {
      continue;
    }
    moduleSourceRefs.set(schedule.sourceId, {
      sourceKind: "module",
      logicalPath: schedule.logicalPath,
      sourceId: schedule.sourceId,
    });
  }

  if (manifest.sandbox !== null) {
    moduleSourceRefs.set(manifest.sandbox.sourceId, {
      exportName: manifest.sandbox.exportName,
      sourceKind: "module",
      logicalPath: manifest.sandbox.logicalPath,
      sourceId: manifest.sandbox.sourceId,
    });
  }

  // Extension mount modules (root manifest only). Their top-level factory call
  // binds config, so they must be evaluated at module-map load.
  const extensionMounts = (manifest as { extensionMounts?: readonly CompiledExtensionMount[] })
    .extensionMounts;
  if (extensionMounts !== undefined) {
    for (const mount of extensionMounts) {
      moduleSourceRefs.set(mount.mountSourceId, {
        sourceKind: "module",
        logicalPath: mount.mountLogicalPath,
        sourceId: mount.mountSourceId,
      });
    }
  }

  // Authored system modules execute once at build time. The compiled markdown
  // is captured into the manifest, so there is no need to include them in the
  // runtime module map.

  return [...moduleSourceRefs.values()];
}

function createImportSpecifier(input: {
  fromDirectory: string;
  importSpecifierStyle: "absolute" | "relative";
  targetPath: string;
}): string {
  if (input.importSpecifierStyle === "absolute") {
    return normalizeEsmImportSpecifier(normalizeFilesystemPath(input.targetPath));
  }

  const relativeSpecifier = relativeFilesystemPath(input.fromDirectory, input.targetPath);

  if (relativeSpecifier.startsWith(".")) {
    return relativeSpecifier;
  }

  return `./${relativeSpecifier}`;
}

function renderModuleMap(scopes: readonly CollectedModuleNodeScope[]): string {
  return renderFrozenObject(
    [
      {
        key: "nodes",
        value: renderFrozenObject(
          scopes.map((scope) => ({
            key: scope.nodeId,
            value: renderFrozenObject(
              [
                {
                  key: "modules",
                  value: renderFrozenObject(
                    scope.modules.map((moduleImport) => ({
                      key: moduleImport.sourceId,
                      value: moduleImport.bindingName,
                    })),
                  ),
                },
              ],
              3,
            ),
          })),
        ),
      },
    ],
    0,
  );
}

function renderFrozenObject(
  entries: ReadonlyArray<{
    key: string;
    value: string;
  }>,
  depth: number = 1,
): string {
  if (entries.length === 0) {
    return "Object.freeze({})";
  }

  const indentation = "  ".repeat(depth);
  const nestedIndentation = "  ".repeat(depth + 1);

  return [
    "Object.freeze({",
    entries
      .map((entry) => {
        return `${nestedIndentation}${JSON.stringify(entry.key)}: ${entry.value.replaceAll("\n", `\n${nestedIndentation}`)}`;
      })
      .join(",\n"),
    `${indentation}})`,
  ].join("\n");
}

function dirnameFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);

  if (parsed.segments.length === 0) {
    return parsed.root.length === 0 ? "." : parsed.root;
  }

  return createFilesystemPath(parsed.root, parsed.segments.slice(0, -1));
}

function joinFilesystemPath(base: string, next: string): string {
  const parsedBase = splitFilesystemPath(base);
  const parsedNext = splitFilesystemPath(next);

  if (parsedNext.root.length > 0) {
    return createFilesystemPath(parsedNext.root, parsedNext.segments);
  }

  return createFilesystemPath(parsedBase.root, [...parsedBase.segments, ...parsedNext.segments]);
}

function relativeFilesystemPath(fromDirectory: string, targetPath: string): string {
  const from = splitFilesystemPath(fromDirectory);
  const target = splitFilesystemPath(targetPath);

  if (from.root !== target.root) {
    return normalizeFilesystemPath(targetPath);
  }

  let sharedIndex = 0;

  while (
    sharedIndex < from.segments.length &&
    sharedIndex < target.segments.length &&
    from.segments[sharedIndex] === target.segments[sharedIndex]
  ) {
    sharedIndex += 1;
  }

  const relativeSegments = [
    ...Array.from({ length: from.segments.length - sharedIndex }, () => ".."),
    ...target.segments.slice(sharedIndex),
  ];

  return relativeSegments.length === 0 ? "." : relativeSegments.join("/");
}

function normalizeFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);
  return createFilesystemPath(parsed.root, parsed.segments);
}

function splitFilesystemPath(path: string): {
  readonly root: string;
  readonly segments: string[];
} {
  const normalized = path.replaceAll("\\", "/");
  let root = "";
  let remainder = normalized;

  const windowsDriveMatch = normalized.match(/^[A-Za-z]:/);

  if (windowsDriveMatch !== null) {
    root = windowsDriveMatch[0];
    remainder = normalized.slice(root.length);

    if (remainder.startsWith("/")) {
      root = `${root}/`;
      remainder = remainder.slice(1);
    }
  } else if (normalized.startsWith("/")) {
    root = "/";
    remainder = normalized.slice(1);
  }

  const segments: string[] = [];

  for (const segment of remainder.split("/")) {
    if (segment.length === 0 || segment === ".") {
      continue;
    }

    if (segment === "..") {
      if (segments.length > 0 && segments[segments.length - 1] !== "..") {
        segments.pop();
        continue;
      }

      if (root.length === 0) {
        segments.push(segment);
      }

      continue;
    }

    segments.push(segment);
  }

  return {
    root,
    segments,
  };
}

function createFilesystemPath(root: string, segments: readonly string[]): string {
  if (root === "/") {
    return segments.length === 0 ? "/" : `/${segments.join("/")}`;
  }

  if (root.endsWith("/")) {
    return segments.length === 0 ? root : `${root}${segments.join("/")}`;
  }

  if (root.length > 0) {
    return segments.length === 0 ? root : `${root}/${segments.join("/")}`;
  }

  return segments.length === 0 ? "." : segments.join("/");
}
