/**
 * Telegram HITL inline keyboard rendering and compact callback decode helpers.
 *
 * Telegram limits `InlineKeyboardButton.callback_data` to 64 bytes, so
 * eve stores compact callback ids in durable channel state and remaps
 * them back to full input responses inside the channel deliver hook.
 */

import type { InputRequest, InputResponse } from "#runtime/input/types.js";

/** Prefix used in Telegram callback_data values generated by eve. */
export const TELEGRAM_HITL_CALLBACK_PREFIX = "eve:";

/** Synthetic request id prefix sent through `send()` for callback queries. */
export const TELEGRAM_CALLBACK_RESPONSE_PREFIX = "telegram_callback:";

/** Synthetic request id prefix sent through `send()` for replies to ForceReply prompts. */
export const TELEGRAM_REPLY_RESPONSE_PREFIX = "telegram_reply:";

const TELEGRAM_BUTTON_LABEL_MAX_LENGTH = 64;
const TELEGRAM_INPUT_PLACEHOLDER_MAX_LENGTH = 64;
const TELEGRAM_PROMPT_MAX_LENGTH = 4000;
const TELEGRAM_INLINE_ROW_SIZE = 2;

/**
 * Durable HITL state. `hitlCallbacks` maps compact callback ids to their stored
 * `InputResponse`. `nextHitlCallbackId` is the monotonic id counter.
 * `pendingFreeformReplies` maps a posted prompt's message id to the awaiting
 * requestId.
 */
export interface TelegramHitlState {
  hitlCallbacks?: Record<string, InputResponse>;
  nextHitlCallbackId?: number;
  pendingFreeformReplies?: Record<string, string>;
}

/**
 * Rendered Telegram message body for one pending input request.
 * `freeformRequestId` is set only for ForceReply prompts (option-less requests).
 * After posting such a prompt, call {@link registerTelegramFreeformPrompt}.
 * Option requests instead carry an inline-keyboard `replyMarkup`.
 */
export interface TelegramInputRequestMessage {
  readonly freeformRequestId?: string;
  readonly replyMarkup?: Readonly<Record<string, unknown>>;
  readonly text: string;
}

/** Renders one `InputRequest` as Telegram inline keyboard or ForceReply markup. */
export function renderTelegramInputRequest(
  request: InputRequest,
  state: TelegramHitlState,
): TelegramInputRequestMessage {
  const options = request.options;
  if (options && options.length > 0) {
    const buttons = options.map((option) => ({
      callback_data: registerTelegramCallback(state, {
        optionId: option.id,
        requestId: request.requestId,
      }),
      text: truncate(option.label, TELEGRAM_BUTTON_LABEL_MAX_LENGTH),
    }));
    return {
      replyMarkup: {
        inline_keyboard: chunk(buttons, TELEGRAM_INLINE_ROW_SIZE),
      },
      text: truncate(request.prompt, TELEGRAM_PROMPT_MAX_LENGTH),
    };
  }

  return {
    freeformRequestId: request.requestId,
    replyMarkup: {
      force_reply: true,
      input_field_placeholder: truncate("Type your answer", TELEGRAM_INPUT_PLACEHOLDER_MAX_LENGTH),
      selective: true,
    },
    text: truncate(request.prompt, TELEGRAM_PROMPT_MAX_LENGTH),
  };
}

/** Records the Telegram message id that a freeform answer should reply to. */
export function registerTelegramFreeformPrompt(
  state: TelegramHitlState,
  input: { readonly messageId: string; readonly requestId: string },
): void {
  state.pendingFreeformReplies = {
    ...state.pendingFreeformReplies,
    [input.messageId]: input.requestId,
  };
}

/**
 * Wraps Telegram callback data as a synthetic `InputResponse` (requestId prefixed
 * with `telegram_callback:`, optionId hardcoded to `"selected"`). It is a
 * placeholder; {@link resolveTelegramInputResponses} resolves it back to the real
 * stored response.
 */
export function telegramCallbackInputResponse(callbackData: string): InputResponse {
  return {
    optionId: "selected",
    requestId: `${TELEGRAM_CALLBACK_RESPONSE_PREFIX}${callbackData}`,
  };
}

/** Wraps a reply-to-message id in an `InputResponse` shape for delivery. */
export function telegramReplyInputResponse(input: {
  readonly messageId: string;
  readonly text: string;
}): InputResponse {
  return {
    requestId: `${TELEGRAM_REPLY_RESPONSE_PREFIX}${input.messageId}`,
    text: input.text,
  };
}

/** True when an input response needs Telegram-specific durable-state remapping. */
export function isTelegramSyntheticResponse(response: InputResponse): boolean {
  return (
    response.requestId.startsWith(TELEGRAM_CALLBACK_RESPONSE_PREFIX) ||
    response.requestId.startsWith(TELEGRAM_REPLY_RESPONSE_PREFIX)
  );
}

/** Remaps compact Telegram callback/reply ids into real eve input responses. */
export function resolveTelegramInputResponses(
  state: TelegramHitlState,
  responses: readonly InputResponse[],
): InputResponse[] {
  const resolved: InputResponse[] = [];

  for (const response of responses) {
    if (response.requestId.startsWith(TELEGRAM_CALLBACK_RESPONSE_PREFIX)) {
      const callbackData = response.requestId.slice(TELEGRAM_CALLBACK_RESPONSE_PREFIX.length);
      const mapped = state.hitlCallbacks?.[callbackData];
      if (mapped !== undefined) {
        resolved.push(mapped);
        delete state.hitlCallbacks?.[callbackData];
      }
      continue;
    }

    if (response.requestId.startsWith(TELEGRAM_REPLY_RESPONSE_PREFIX)) {
      const messageId = response.requestId.slice(TELEGRAM_REPLY_RESPONSE_PREFIX.length);
      const requestId = state.pendingFreeformReplies?.[messageId];
      if (requestId !== undefined && response.text !== undefined) {
        resolved.push({ requestId, text: response.text });
        delete state.pendingFreeformReplies?.[messageId];
      }
      continue;
    }

    resolved.push(response);
  }

  return resolved;
}

function registerTelegramCallback(state: TelegramHitlState, response: InputResponse): string {
  const next = state.nextHitlCallbackId ?? 0;
  state.nextHitlCallbackId = next + 1;
  const callbackData = `${TELEGRAM_HITL_CALLBACK_PREFIX}${next.toString(36)}`;
  state.hitlCallbacks = {
    ...state.hitlCallbacks,
    [callbackData]: response,
  };
  return callbackData;
}

function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) return value;
  const sliceLength = Math.max(0, maxLength - 3);
  return `${value.slice(0, sliceLength).trimEnd()}...`;
}

function chunk<T>(values: readonly T[], size: number): T[][] {
  const result: T[][] = [];
  for (let index = 0; index < values.length; index += size) {
    result.push(values.slice(index, index + size));
  }
  return result;
}
